-- ============================================================
-- SVOM DELOVODNIK v13 — SUPABASE SETUP
-- Zaženi celotno datoteko v Supabase > SQL Editor > Run.
-- ============================================================

create extension if not exists pgcrypto;

-- 1. OSEBE
create table if not exists public.svom_users (
  id bigint generated by default as identity primary key,
  code text not null unique,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

-- 2. VRSTE DELA
create table if not exists public.svom_work_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default 'gray'
    check (color in ('red','yellow','green','gray')),
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

-- 3. KATEGORIJE
create table if not exists public.svom_categories (
  id bigint generated by default as identity primary key,
  work_type_id bigint not null references public.svom_work_types(id) on delete cascade,
  name text not null,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  unique(work_type_id, name)
);

-- 4. PODKATEGORIJE
create table if not exists public.svom_subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.svom_categories(id) on delete cascade,
  name text not null,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  unique(category_id, name)
);

-- 5. LOKACIJE
create table if not exists public.svom_locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

-- 6. DELOVODNIK
create table if not exists public.svom_worklog (
  id uuid primary key default gen_random_uuid(),
  work_date date not null,
  work_type text not null,
  category text,
  subcategory text,
  location text,
  leader text,
  crew text[] not null default '{}',
  description text not null default '',
  materials text,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists svom_worklog_work_date_idx
  on public.svom_worklog(work_date desc);

-- updated_at trigger
create or replace function public.svom_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists svom_worklog_set_updated_at on public.svom_worklog;
create trigger svom_worklog_set_updated_at
before update on public.svom_worklog
for each row execute function public.svom_set_updated_at();

-- ============================================================
-- RLS
-- Ta konfiguracija omogoča uporabo s Publishable/anon ključem.
-- Primerna je za interno/testno uporabo brez prave avtentikacije.
-- Če stran objaviš javno, dodaj pravo Supabase Auth zaščito.
-- ============================================================

alter table public.svom_users enable row level security;
alter table public.svom_work_types enable row level security;
alter table public.svom_categories enable row level security;
alter table public.svom_subcategories enable row level security;
alter table public.svom_locations enable row level security;
alter table public.svom_worklog enable row level security;

drop policy if exists "svom_users_all_anon" on public.svom_users;
create policy "svom_users_all_anon"
on public.svom_users for all to anon
using (true) with check (true);

drop policy if exists "svom_work_types_all_anon" on public.svom_work_types;
create policy "svom_work_types_all_anon"
on public.svom_work_types for all to anon
using (true) with check (true);

drop policy if exists "svom_categories_all_anon" on public.svom_categories;
create policy "svom_categories_all_anon"
on public.svom_categories for all to anon
using (true) with check (true);

drop policy if exists "svom_subcategories_all_anon" on public.svom_subcategories;
create policy "svom_subcategories_all_anon"
on public.svom_subcategories for all to anon
using (true) with check (true);

drop policy if exists "svom_locations_all_anon" on public.svom_locations;
create policy "svom_locations_all_anon"
on public.svom_locations for all to anon
using (true) with check (true);

drop policy if exists "svom_worklog_all_anon" on public.svom_worklog;
create policy "svom_worklog_all_anon"
on public.svom_worklog for all to anon
using (true) with check (true);

grant usage on schema public to anon;
grant select, insert, update, delete on
  public.svom_users,
  public.svom_work_types,
  public.svom_categories,
  public.svom_subcategories,
  public.svom_locations,
  public.svom_worklog
to anon;
grant usage, select on all sequences in schema public to anon;

-- ============================================================
-- ZAČETNI PODATKI
-- ============================================================

insert into public.svom_users (code, sort_order) values
('RŠ',10),('GT',20),('TG',30),('BL',40),('RK',50),('JP',60),('AG',70),('IĐ',80)
on conflict (code) do nothing;

insert into public.svom_work_types (name,color,sort_order) values
('Vzdrževanje','yellow',10),
('Intervencije','red',20),
('Dela in opravila','green',30)
on conflict (name) do update set color=excluded.color, sort_order=excluded.sort_order;

-- Kategorije
insert into public.svom_categories (work_type_id,name,sort_order)
select wt.id, x.name, x.sort_order
from public.svom_work_types wt
join (values
  ('Vzdrževanje','avti',10),
  ('Vzdrževanje','plovila',20),
  ('Vzdrževanje','prostor',30),
  ('Vzdrževanje','OVP',40),
  ('Intervencije','onesnaženje',10),
  ('Intervencije','ovire na morju',20),
  ('Intervencije','kadavri',30),
  ('Dela in opravila','vzorčenje ARSO',10),
  ('Dela in opravila','ostala dela',20)
) as x(work_type,name,sort_order)
  on wt.name=x.work_type
on conflict (work_type_id,name) do nothing;

-- Podkategorije
insert into public.svom_subcategories (category_id,name,sort_order)
select c.id, x.subcategory, x.sort_order
from public.svom_categories c
join public.svom_work_types wt on wt.id=c.work_type_id
join (values
  ('Vzdrževanje','avti','n/a',10),

  ('Vzdrževanje','plovila','SI-10',10),
  ('Vzdrževanje','plovila','SI-11',20),
  ('Vzdrževanje','plovila','SI-12',30),
  ('Vzdrževanje','plovila','SI-13',40),
  ('Vzdrževanje','plovila','SI-20',50),
  ('Vzdrževanje','plovila','SI-21',60),
  ('Vzdrževanje','plovila','SI-22',70),

  ('Vzdrževanje','prostor','Sedež URSP',10),
  ('Vzdrževanje','prostor','Skladišče SVOM',20),
  ('Vzdrževanje','prostor','Izpostava Izola',30),
  ('Vzdrževanje','prostor','Izpostava Piran',40),

  ('Vzdrževanje','OVP','boja',10),
  ('Vzdrževanje','OVP','svetilnik',20),
  ('Vzdrževanje','OVP','kamnit svetilnik',30),

  ('Intervencije','onesnaženje','ogljikovodiki',10),
  ('Intervencije','onesnaženje','kosovno',20),
  ('Intervencije','onesnaženje','ostalo',30),

  ('Intervencije','ovire na morju','naplavine',10),
  ('Intervencije','ovire na morju','plovila',20),
  ('Intervencije','ovire na morju','ostalo',30),

  ('Intervencije','kadavri','želva',10),
  ('Intervencije','kadavri','delfin',20),
  ('Intervencije','kadavri','divjad',30),
  ('Intervencije','kadavri','ostalo',40)
) as x(work_type,category,subcategory,sort_order)
  on wt.name=x.work_type and c.name=x.category
on conflict (category_id,name) do nothing;

-- Lokacije
insert into public.svom_locations (name,sort_order) values
('TM RS',10),
('Morje Koper',20),
('Morje Izola',30),
('Morje Piran',40),
('Lazaret',50),
('Debeli rtič',60),
('Ankaran',70),
('Luka Koper',80),
('Koper',90),
('Semedela',100),
('Rex',110),
('Ladjedelnica Izola',120),
('Izola',130),
('Mestno pristanišče Izola',140),
('Marina Izola',150),
('San Simon',160),
('Bele skale 1',170),
('Bele skale 2',180),
('Meseči zaliv',190),
('Strunjan',200),
('Soline Strunjan',210),
('Pacug',220),
('Fijesa',230),
('pod cerkvijo Piran',240),
('Rt Madona',250),
('Piran',260),
('Fornače',270),
('Bernardin',280),
('Skladišča soli',290),
('Portorož',300),
('Lucija',310),
('Marina Portorož',320),
('Seča',330),
('Sečoveljske soline',340)
on conflict (name) do nothing;


-- ============================================================
-- SVOM.OS v25 — centralno stanje dodatnih modulov
-- ============================================================
create table if not exists public.svom_os_state (
  key text primary key,
  value jsonb,
  updated_by text,
  updated_at timestamptz not null default now()
);

alter table public.svom_os_state enable row level security;
drop policy if exists "svom_os_state_all_anon" on public.svom_os_state;
create policy "svom_os_state_all_anon"
on public.svom_os_state for all to anon
using (true) with check (true);

grant select, insert, update, delete on public.svom_os_state to anon;

-- Zaseben bucket za priponke. Dostop je dovoljen aplikaciji prek publishable/anon ključa.
insert into storage.buckets (id,name,public)
values ('svom-os-attachments','svom-os-attachments',false)
on conflict (id) do update set public=false;

drop policy if exists "svom_os_storage_select_anon" on storage.objects;
create policy "svom_os_storage_select_anon"
on storage.objects for select to anon
using (bucket_id='svom-os-attachments');

drop policy if exists "svom_os_storage_insert_anon" on storage.objects;
create policy "svom_os_storage_insert_anon"
on storage.objects for insert to anon
with check (bucket_id='svom-os-attachments');

drop policy if exists "svom_os_storage_update_anon" on storage.objects;
create policy "svom_os_storage_update_anon"
on storage.objects for update to anon
using (bucket_id='svom-os-attachments')
with check (bucket_id='svom-os-attachments');

drop policy if exists "svom_os_storage_delete_anon" on storage.objects;
create policy "svom_os_storage_delete_anon"
on storage.objects for delete to anon
using (bucket_id='svom-os-attachments');
